
server:
  port: 8080

bettertogether:
  jwt:
    secret: D072B91E266D766203E267FA30634A12C52CDC85BC667A5171B000B92E2DCC50
    expiration: 8888888

spring:
  application:
    name: bettertogether

---
# Profiles for dev

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jackson:
    serialization.indent_output: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/database  #jdbc:h2:mem:test;
    username: sa
    password:

  jpa:
    database: H2
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


---
# Profile for heroku deployment
spring:
  profiles: heroku

  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    url: ${DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

